(function(root,factory){'use strict';if(typeof module!=='undefined'&&module.exports)module.exports=factory;else root.CopaFan=factory(root.Torneo);})(typeof window!=='undefined'?window:this,function(C){
 'use strict';
 const order=(a,b)=>(a.date||'9999').localeCompare(b.date||'9999')||(a.time||'99:99').localeCompare(b.time||'99:99')||String(a.id).localeCompare(String(b.id));
 const inCourt=g=>g.status==='jugado'&&!g.bye&&(g.forfeit??'ninguno')==='ninguno';
 function model(t,entryId){const entry=t.entries.find(e=>e.id===entryId);if(!entry)throw Error('Equipo no inscrito en esta edición.');const division=t.divisions.find(d=>d.id===entry.divisionId),team=t.teams.find(x=>x.id===entry.teamId),games=t.games.filter(g=>g.divisionId===entry.divisionId&&!g.bye&&(g.home===entryId||g.away===entryId)),scheduled=games.filter(g=>g.status==='programado').sort(order),played=games.filter(g=>g.status==='jugado').sort(order).reverse(),court=played.filter(inCourt),stats=C.stats(t,entry.divisionId),performance=stats.teams.find(e=>e.entryId===entryId),players=stats.players.filter(p=>p.entryId===entryId).sort((a,b)=>b.points-a.points||a.name.localeCompare(b.name)),standingRows=entry.groupId?C.standings(t,entry.divisionId,entry.groupId):[],position=standingRows.findIndex(e=>e.entryId===entryId),standing=standingRows[position];
 let streak=0;for(const g of court){if(C.winner(g)!==entryId)break;streak++;}
 const groupGames=t.games.filter(g=>g.divisionId===entry.divisionId&&g.groupId===entry.groupId&&g.phase==='groups'&&!g.bye&&g.status!=='cancelado'),groupClosed=groupGames.length>0&&groupGames.every(g=>g.status==='jugado'),insights=[];
 if(streak>=2)insights.push({label:'EN RACHA',value:String(streak),text:streak+' victorias consecutivas en cancha'});
 if(standing&&standing.played)insights.push({label:'POSICIÓN EN EL GRUPO',value:(position+1)+'º',text:(groupClosed&&!standing.tied?'Grupo completado':'Posición provisional')+' · '+standing.won+' victorias · '+standing.lost+' derrotas'});
 if(performance?.played){insights.push({label:'ATAQUE',value:(performance.pf/performance.played).toFixed(1),text:'puntos a favor por juego'});const others=stats.teams.filter(p=>p.played);const best=Math.min(...others.map(p=>p.pc/p.played));const shared=others.filter(p=>Math.abs(p.pc/p.played-best)<1e-9).length;insights.push({label:'DEFENSA',value:(performance.pc/performance.played).toFixed(1),text:'puntos recibidos por juego'+(others.length>1&&Math.abs(performance.pc/performance.played-best)<1e-9?' · Menor promedio'+(shared>1?' compartido':'')+' de la categoría':'')});}
 let featured=null;for(const g of court){const player=entry.roster.find(p=>p.id===g.mvp),side=g.home===entryId?'home':'away',line=(g[side+'Stats']??[]).find(p=>p.playerId===player?.id);if(player&&line){featured={player,points:line.points,threes:line.threes,gameId:g.id,label:'ÚLTIMO MVP DE TU EQUIPO',scope:[g.date,g.time].filter(Boolean).join(' · ')};break;}}
 if(!featured&&players.length){const p=players[0],player=entry.roster.find(x=>x.id===p.id);if(player)featured={player,points:p.points,threes:p.threes,gameId:null,label:'LÍDER DE PUNTOS DE TU EQUIPO',scope:'Acumulado del torneo · '+p.played+' juegos'};}
 const bracket=t.games.filter(g=>g.divisionId===entry.divisionId&&g.phase==='knockout'),rounds=[...new Set(bracket.map(g=>g.round))].sort((a,b)=>a-b),seeded=(division.bracketSeeds??[]).includes(entryId)||bracket.some(g=>g.home===entryId||g.away===entryId),journey=[{label:'Fase de grupos',state:groupClosed?'Grupo completado':groupGames.length?'En competencia':'Por programar',tone:groupClosed?'complete':'current'}];
 let eliminated=false,champion=false;
 for(const round of rounds){const list=bracket.filter(g=>g.round===round),game=list.find(g=>g.home===entryId||g.away===entryId);let state='Por definir',tone='pending';if(game){if(game.bye){state='Pase libre';tone='complete';}else if(game.status==='jugado'){const won=C.winner(game)===entryId;if(won){champion=round===rounds.at(-1);state=champion?'Campeón':'Victoria · Avanza';tone='complete';}else{eliminated=true;state='Participación concluida';tone='out';}}else if(game.status==='cancelado'){state='Juego cancelado';tone='pending';}else{state='Próximo reto';tone='current';}}else if(eliminated){state='Sin participación';tone='out';}else if(!seeded&&groupClosed){state='Sin cruce asignado';}journey.push({label:C.roundName(t,list[0]),state,tone,gameId:game?.id??null});}
 if(!rounds.length)journey.push({label:'Eliminatorias',state:'Clasificación por confirmar',tone:'pending'});
 return {entry,division,team,scheduled,played,court,stats,performance,players,standing,position,streak,insights,featured,journey,champion};
 }
 return {model,order,inCourt};
});
