const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const C=require('../js/torneos-core.js'),storage=require('../js/torneos-storage.js'),Share=require('../js/copa-share.js');
function fixture(){const t=C.create('Copa 2026'),d=C.division('Libre','Femenil');t.divisions=[d];d.groups=[{id:'g',name:'A'}];for(let i=0;i<3;i++){t.teams.push({id:'t'+i,name:'Equipo '+i});t.entries.push({id:'e'+i,teamId:'t'+i,divisionId:d.id,groupId:'g',roster:[{id:'p'+i,name:'Jugadora '+i,number:'12',photo:'img/torneos/'+t.id+'/foto.png'}]});}t.games=C.groupGames(t,d.id);return t;}
function result(t,g,forfeit=false){return C.result(t,g.id,{homeScore:forfeit?20:60,awayScore:forfeit?0:40,forfeit:forfeit?'away':'ninguno',homeStats:forfeit?[]:[{playerId:'p'+g.home.slice(1),points:60,threes:4,fouls:2}],awayStats:forfeit?[]:[{playerId:'p'+g.away.slice(1),points:40,threes:2,fouls:1}],statsComplete:true,mvp:forfeit?'':'p'+g.home.slice(1)});}
test('visibility is independent of every lifecycle state, with hidden new editions and legacy tests',()=>{const t=C.create('Copa');assert.equal(C.isPublic(t),false);for(const status of ['borrador','publicado','finalizado','archivado']){assert.equal(C.isPublic({...t,status,visible:true}),true);assert.equal(C.isPublic({...t,status,visible:false}),false);}assert.equal(C.isPublic({name:'Prueba',status:'publicado'}),false);assert.equal(C.isPublic({name:'Copa 2026',status:'publicado'}),true);});
test('public catalog and direct links reject hidden editions; token administration can load them',async()=>{const t=fixture(),shown={...t,id:'tor-ab',visible:true};const s=storage({core:C,getToken:()=> 'test',fetcher:async url=>({ok:true,status:200,json:async()=>url.includes('/contents/')?{sha:'s',content:Buffer.from(JSON.stringify(t)).toString('base64')}:url.endsWith('index.json')?{torneos:[t,shown]}:t})});assert.deepEqual((await s.catalog(false)).torneos.map(x=>x.id),['tor-ab']);await assert.rejects(s.load(t.id,false),/oculta/);assert.equal((await s.load(t.id,true)).data.id,t.id);});
test('forfeits have no contribution to any performance denominator or metric but retain standing points',()=>{let t=fixture();t=result(t,t.games[0]);const before=C.stats(t,t.divisions[0].id);t=result(t,t.games[1],true);assert.deepEqual(C.stats(t,t.divisions[0].id),before);const rows=C.standings(t,t.divisions[0].id,'g');assert.equal(rows.reduce((n,x)=>n+x.played,0),4);assert.equal(rows.reduce((n,x)=>n+x.points,0),5);const fresh=fixture(),only=result(fresh,fresh.games[0],true);assert.equal(C.stats(only,only.divisions[0].id).teams.length,0);});
test('shared result and featured player resolve names, photo and achievements from the same capture',()=>{let t=fixture();t=result(t,t.games[0]);const g=t.games[0],m=Share.model(t,g.id,true);assert.equal(m.player.name,'Jugadora '+g.home.slice(1));assert.equal(m.player.points,60);assert.equal(m.player.threes,4);assert.equal(m.player.photo,t.entries.find(e=>e.id===g.home).roster[0].photo);assert.equal(m.category,'Libre · Femenil');assert.equal(m.edition,'Copa 2026');t=result(t,t.games[1],true);assert.throws(()=>Share.model(t,t.games[1].id,true),/destacado/);assert.equal(Share.model(t,t.games[1].id).forfeit,true);});
test('share poster omits score-sheet recognition note and uses institutional colors',()=>{const src=fs.readFileSync(path.join(__dirname,'../js/copa-share.js'),'utf8');assert.doesNotMatch(src,/reconocimiento registrado|hoja del juego/i);for(const color of ['#751b3c','#f8e9a7','#fff'])assert.ok(src.includes(color));});
test('photo and tournament write atomically to piensa; public reads never carry the saved token',async()=>{const t=fixture(),calls=[],photo=t.entries[0].roster[0].photo;const s=storage({core:C,getToken:()=> 'test-token',fetcher:async(url,init={})=>{calls.push({url,init});let data={},status=200;const p=url.split('/piensa')[1];if(p==='/git/ref/heads/main')data={object:{sha:'head'}};else if(p?.startsWith('/contents/'))status=404;else if(p==='/git/commits/head')data={tree:{sha:'base'}};else if(p==='/git/blobs')data={sha:'blob'+calls.length};else data={sha:'new',torneos:[]};return {ok:status===200,status,json:async()=>data};}});await s.save(t,null,{[photo]:'cG5n'});const tree=JSON.parse(calls.find(x=>x.url.endsWith('/git/trees')).init.body);assert.ok(tree.tree.some(x=>x.path===photo));assert.ok(calls.every(x=>x.url.startsWith('https://api.github.com/repos/inproneg77/piensa/')));const summary=JSON.parse(JSON.parse(calls.filter(x=>x.url.endsWith('/git/blobs'))[1].init.body).content);assert.equal(summary.torneos[0].visible,false);calls.length=0;await s.catalog(false);assert.equal(calls[0].init.headers,undefined);});
