const {test}=require('node:test'),assert=require('node:assert/strict');
const C=require('../js/torneos-core.js'),Fan=require('../js/copa-fan.js')(C),Share=require('../js/copa-share.js');
function fixture(){const t=C.create('Copa'),d=C.division('Libre','Femenil');d.groups=[{id:'g',name:'A'}];t.divisions=[d];for(let i=0;i<3;i++){t.teams.push({id:'t'+i,name:'Equipo '+i});t.entries.push({id:'e'+i,teamId:'t'+i,divisionId:d.id,groupId:'g',roster:[{id:'p'+i,name:'Jugadora '+i,photo:'foto'+i}]});}t.games=C.groupGames(t,d.id);t.games.forEach((g,i)=>{g.date='2026-10-'+(10+i);g.time='19:00';});return t;}
function play(t,g,winner,forfeit=false){const home=winner===g.home;return C.result(t,g.id,{homeScore:forfeit?(home?20:0):(home?60:30),awayScore:forfeit?(home?0:20):(home?30:60),forfeit:forfeit?(home?'away':'home'):'ninguno',statsComplete:!forfeit,homeStats:forfeit?[]:[{playerId:'p'+g.home.slice(1),points:home?60:30,threes:2,fouls:0}],awayStats:forfeit?[]:[{playerId:'p'+g.away.slice(1),points:home?30:60,threes:1,fouls:0}],mvp:forfeit?'':'p'+winner.slice(1)});}
test('fan stories exclude forfeits while positions retain them and model is read-only',()=>{let t=fixture();const own=t.games.filter(g=>g.home==='e0'||g.away==='e0');t=play(t,own[0],'e0');t=play(t,own[1],'e0',true);const before=JSON.stringify(t),m=Fan.model(t,'e0');assert.equal(m.performance.played,1);assert.equal(m.performance.pf,60);assert.equal(m.standing.won,2);assert.equal(m.streak,1);assert.equal(m.played.length,2);assert.equal(m.featured.player.id,'p0');assert.equal(m.featured.points,60);assert.equal(JSON.stringify(t),before);});
test('favorite registration isolates schedules, portraits and stories across categories',()=>{const t=fixture(),d=C.division('40+','Varonil');t.divisions.push(d);t.entries.push({id:'other',teamId:'t0',divisionId:d.id,groupId:'',roster:[{id:'foreign',name:'Otro'}]});const m=Fan.model(t,'other');assert.equal(m.scheduled.length,0);assert.equal(m.players.length,0);assert.equal(m.featured,null);assert.equal(m.standing,undefined);assert.throws(()=>Fan.model(t,'missing'),/inscrito/);});
test('latest own MVP is linked to the capture; opponent MVP cannot become favorite MVP',()=>{let t=fixture(),own=t.games.filter(g=>g.home==='e0'||g.away==='e0');t=play(t,own[0],'e0');t=play(t,own[1],own[1].home==='e0'?own[1].away:own[1].home);const m=Fan.model(t,'e0');assert.equal(m.featured.player.id,'p0');assert.equal(m.featured.gameId,own[0].id);assert.equal(m.streak,0);});
test('complete group does not invent qualification; real rounds track winner and elimination',()=>{let t=fixture();for(const g of [...t.games])t=play(t,g,[g.home,g.away].sort()[0]);assert.equal(Fan.model(t,'e0').journey.at(-1).state,'Clasificación por confirmar');const d=t.divisions[0];d.bracketSeeds=['e0','e1'];t.games.push(...C.bracket(t,d.id,d.bracketSeeds));let final=t.games.find(g=>g.phase==='knockout');assert.equal(Fan.model(t,'e0').journey.at(-1).label,'Final');assert.equal(Fan.model(t,'e0').champion,false);t=play(t,final,'e0');assert.equal(Fan.model(t,'e0').champion,true);assert.equal(Fan.model(t,'e0').journey.at(-1).state,'Campeón');assert.equal(Fan.model(t,'e1').journey.at(-1).state,'Participación concluida');});
test('scheduled poster has actual teams and schedule and never invents a result or MVP',()=>{const t=fixture(),g=t.games[0];const m=Share.model(t,g.id,'fixture');assert.equal(m.fixture,true);assert.equal(m.player,null);assert.equal(m.time,'19:00');assert.equal(m.sides[0].name,C.teamName(t,g.home));assert.throws(()=>Share.model(t,g.id),/resultado/);g.status='cancelado';assert.throws(()=>Share.model(t,g.id,'fixture'));});
