const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const C=require('../js/torneos-core.js');
function app(admin=true){
 const nodes=new Map(),local=new Map([['piensa_gh_token','test-only']]);
 const element=()=>({innerHTML:'',textContent:'',value:'',hidden:false,dataset:{},addEventListener(){},reset(){},querySelector(){return element();},querySelectorAll(){return [];},showModal(){},close(){}});
 const get=id=>{if(!nodes.has(id))nodes.set(id,element());return nodes.get(id);};let saved,savedImages;
 const storage={save:async (t,sha,images)=>{savedImages=images;saved=C.clone(t);return {sha:'saved'};},load:async()=>({data:C.clone(saved),sha:'saved'})};
 const ctx=vm.createContext({readSavedImages:()=>savedImages,Torneo:C,crypto:crypto.webcrypto,URLSearchParams,location:{search:admin?'?administrar=1':''},history:{replaceState(){}},window:{addEventListener(){}},document:{getElementById:get,addEventListener(){},createElement(){return {getContext(){return {drawImage(){}};},toDataURL(){return 'data:image/png;base64,cG5n';}};}},Image:class{constructor(){this.naturalWidth=100;this.naturalHeight=100;}set src(v){queueMicrotask(()=>this.onload());}},localStorage:{getItem:k=>local.get(k)||null,setItem:(k,v)=>local.set(k,v),removeItem:k=>local.delete(k)},createTournamentStorage:()=>storage,CopaConfig:{brand(){},assetBase:'https://example.test/',imageBase:'https://example.test/'},URL:class extends URL{static createObjectURL(){return 'blob:test';}static revokeObjectURL(){}},queueMicrotask,confirm:()=>true,console,setTimeout,clearTimeout});
 let src=fs.readFileSync(path.join(__dirname,'../js/torneos-ui.js'),'utf8');src=src.slice(0,src.lastIndexOf(' (async()=>'))+`window.ui={set(t){tournament=t;divisionId=t.divisions[0].id;},handle,render,renderFan,renderTeams,renderGames,renderSettings,renderDownloads,html:()=>$('tor-app').innerHTML,content:()=>$('tor-content').innerHTML,division(id){divisionId=id;},local,images:()=>readSavedImages(),fields:()=>$('tor-fields').innerHTML,read:()=>tournament,submit:async values=>{await formCallback(new Map(Object.entries(values)));await save();},reopen:()=>open(tournament.id)};})();`.replace('local,','');
 vm.runInContext(src,ctx);const t=C.create('Prueba');const d=C.division('Libre','Varonil'),other=C.division('Libre','Femenil');t.divisions=[d,other];t.teams=[{id:'team',name:'Equipo',logo:''}];t.entries=[{id:'entry',teamId:'team',divisionId:d.id,groupId:'',roster:[]},{id:'other-entry',teamId:'team',divisionId:other.id,groupId:'',roster:[]}];ctx.window.ui.set(t);return ctx.window.ui;
}
test('team exposes add player; registration survives save/reopen in its own division',async()=>{const ui=app();assert.match(ui.renderTeams(),/Agregar jugador/);await ui.handle('player-new','entry');assert.match(ui.fields(),/Nombre del jugador/);await ui.submit({name:'Ana Pérez',number:'12'});await ui.reopen();assert.equal(ui.read().entries[0].roster[0].name,'Ana Pérez');assert.equal(ui.read().entries[0].roster[0].number,'12');assert.equal(ui.read().entries[1].roster.length,0);await ui.handle('player-new','entry');await assert.rejects(ui.submit({name:'Ana Pérez',number:'8'}),/ya está/);assert.equal(ui.read().entries[0].roster.length,1);});
test('roster opens, edits existing players and adds a batch without losing identity',async()=>{const ui=app();await ui.handle('player-new','entry');await ui.submit({name:'Ana Pérez',number:'12'});const id=ui.read().entries[0].roster[0].id;await ui.handle('roster','entry');assert.match(ui.fields(),/Agregar jugadores/);await ui.submit({name0:'Ana P.',number0:'14',active0:'on',newPlayers:'Luis García | 8\nPedro López | 10'});await ui.reopen();const r=ui.read().entries[0].roster;assert.equal(r.length,3);assert.equal(r[0].id,id);assert.equal(r[0].number,'14');assert.equal(r[2].name,'Pedro López');});
test('public roster opens read-only and rejects add player actions',async()=>{const ui=app(false);await ui.handle('roster','entry');assert.doesNotMatch(ui.fields(),/textarea|name="newPlayers"/);assert.doesNotMatch(ui.renderTeams(),/Agregar jugador/);await assert.rejects(ui.handle('player-new','entry'),/Administrar copa/);});


test('upload and replace player photo preserves ID, capture references and the other division',async()=>{const ui=app();const file={size:20,type:'image/png'};await ui.handle('player-new','entry');assert.match(ui.fields(),/Foto del jugador/);await ui.submit({name:'Ana',number:'7',photoFile:file});await ui.reopen();let p=ui.read().entries[0].roster[0],id=p.id,photo=p.photo;assert.ok(ui.images()[photo]);await ui.handle('roster','entry');await ui.submit({name0:'Ana',number0:'7',active0:'on',photo0:file,newPlayers:''});await ui.reopen();p=ui.read().entries[0].roster[0];assert.equal(p.id,id);assert.notEqual(p.photo,photo);assert.ok(ui.images()[p.photo]);assert.equal(ui.read().entries[1].roster.length,0);await ui.handle('roster','entry');await assert.rejects(ui.submit({name0:'Ana',number0:'7',active0:'on',photo0:{size:30,type:'image/svg+xml'}}),/PNG/);assert.equal(ui.read().entries[0].roster[0].photo,p.photo);});
test('visibility can be edited independently and duplicate editions start empty and hidden',async()=>{const ui=app();await ui.handle('settings');await ui.submit({name:'Copa',start:'',end:'',timezone:'America/Hermosillo',status:'borrador',visible:'si'});assert.equal(ui.read().visible,true);assert.equal(ui.read().status,'borrador');await ui.handle('duplicate');await ui.submit({name:'Copa 2027'});assert.equal(ui.read().visible,false);assert.equal(ui.read().entries.length,0);assert.equal(ui.read().games.length,0);});
test('scheduled games support create, participant edit and removal with recoverable archive',async()=>{const ui=app(),t=ui.read(),d=t.divisions[0];d.groups=[{id:'g',name:'A'}];t.entries[0].groupId='g';for(let i=2;i<4;i++){t.teams.push({id:'t'+i,name:'Equipo '+i});t.entries.push({id:'e'+i,teamId:'t'+i,divisionId:d.id,groupId:'g',roster:[]});}t.venues=[{id:'court',name:'Cancha'}];await ui.handle('game-new');await ui.submit({group:'g',home:'entry',away:'e2',date:'2026-11-06',time:'17:00',venue:'court',duration:'45'});const id=ui.read().games[0].id;await ui.handle('game-edit',id);assert.match(ui.fields(),/name="home"/);await ui.submit({group:'g',home:'entry',away:'e3',date:'2026-11-07',time:'18:00',venue:'court',duration:'45'});assert.equal(ui.read().games[0].away,'e3');assert.equal(ui.read().games[0].time,'18:00');await ui.handle('game-delete',id);assert.equal(ui.read().games.length,0);assert.equal(ui.read().trash[0].value.id,id);});

test('downloads view remains usable when cached HTML has not loaded the report module',()=>{const ui=app();assert.match(ui.renderDownloads(),/Descargar PDF/);assert.match(ui.renderDownloads(),/Equipos, rosters y estadísticas/);});

test('organizer previews fan interface without edit controls or changing hidden visibility',async()=>{const ui=app(),t=ui.read();t.visible=false;const before=JSON.stringify(t);ui.render();assert.match(ui.html(),/Ver como aficionado/);await ui.handle('fan-preview');assert.match(ui.html(),/Volver a administrar/);assert.doesNotMatch(ui.html(),/Guardar cambios del torneo|data-id="captura"|data-id="config"/);assert.doesNotMatch(ui.renderTeams(),/Agregar jugador|Nombre \/ logo/);assert.doesNotMatch(ui.renderGames(),/Agregar Juego|Generar todos/);await assert.rejects(ui.handle('settings'),/Administrar copa/);assert.equal(JSON.stringify(ui.read()),before);await ui.handle('admin-return');assert.match(ui.html(),/Guardar cambios del torneo/);assert.match(ui.renderTeams(),/Agregar jugador/);});

test('following teams is scoped by edition and category, survives navigation, and cannot grant administration',async()=>{const ui=app(false),t=ui.read();await ui.handle('follow','entry');assert.match(ui.content(),/Mi equipo/);assert.match(ui.content(),/Próximos juegos/);await ui.handle('tab','resumen');await ui.handle('tab','miEquipo');assert.match(ui.content(),/value="entry" selected/);ui.division(t.divisions[1].id);assert.doesNotMatch(ui.renderFan(),/value="entry" selected/);await assert.rejects(ui.handle('follow','entry'),/categoría/);await ui.handle('follow','other-entry');ui.division(t.divisions[0].id);assert.match(ui.renderFan(),/value="entry" selected/);await assert.rejects(ui.handle('admin-return'),/administración/);await ui.handle('follow','');assert.match(ui.content(),/Elige tu equipo/);});

test('fan dashboard shows selected team captures, future games and standings without mixing categories or forfeit averages',async()=>{const ui=app(false),t=ui.read(),d=t.divisions[0];d.groups=[{id:'g',name:'Grupo A'}];t.entries[0].groupId='g';t.entries[0].roster=[{id:'p1',name:'Ana aficionada',number:'8'}];t.teams.push({id:'rival',name:'Rival'});t.entries.push({id:'rival-entry',teamId:'rival',divisionId:d.id,groupId:'g',roster:[]});const base={divisionId:d.id,groupId:'g',phase:'groups',home:'entry',away:'rival-entry',date:'2026-11-01',time:'12:00',forfeit:'ninguno',homeStats:[{playerId:'p1',points:30,threes:2,fouls:1}],awayStats:[],statsComplete:true};t.games=[{...base,id:'played',status:'jugado',homeScore:30,awayScore:25},{...base,id:'ff',status:'jugado',homeScore:20,awayScore:0,forfeit:'away',homeStats:[]},{...base,id:'next',status:'programado',date:'2026-11-02'},{...base,id:'other-game',divisionId:t.divisions[1].id,date:'2099-12-31',status:'jugado',homeScore:999,awayScore:0}];await ui.handle('follow','entry');const html=ui.content();assert.match(html,/30\.0 puntos a favor/);assert.match(html,/2 victorias/);assert.match(html,/Ana aficionada/);assert.match(html,/2026-11-02/);assert.doesNotMatch(html,/2099-12-31|999|Editar juego|Capturar resultado/);});

