const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const C=require('../js/torneos-core.js');
function app(admin=true){
 const nodes=new Map(),local=new Map([['piensa_gh_token','test-only']]);
 const element=()=>({innerHTML:'',textContent:'',value:'',hidden:false,dataset:{},addEventListener(){},reset(){},querySelector(){return element();},querySelectorAll(){return [];},showModal(){},close(){}});
 const get=id=>{if(!nodes.has(id))nodes.set(id,element());return nodes.get(id);};let saved;
 const storage={save:async t=>{saved=C.clone(t);return {sha:'saved'};},load:async()=>({data:C.clone(saved),sha:'saved'})};
 const ctx=vm.createContext({Torneo:C,crypto:crypto.webcrypto,URLSearchParams,location:{search:admin?'?administrar=1':''},history:{replaceState(){}},window:{addEventListener(){}},document:{getElementById:get,addEventListener(){}},localStorage:{getItem:k=>local.get(k)||null,setItem:(k,v)=>local.set(k,v),removeItem:k=>local.delete(k)},createTournamentStorage:()=>storage,CopaConfig:{brand(){},assetBase:'https://example.test/',imageBase:'https://example.test/'},URL,confirm:()=>false,console,setTimeout,clearTimeout});
 let src=fs.readFileSync(path.join(__dirname,'../js/torneos-ui.js'),'utf8');src=src.slice(0,src.lastIndexOf(' (async()=>'))+`window.ui={set(t){tournament=t;divisionId=t.divisions[0].id;},handle,renderTeams,fields:()=>$('tor-fields').innerHTML,read:()=>tournament,submit:async values=>{await formCallback(new Map(Object.entries(values)));await save();},reopen:()=>open(tournament.id)};})();`;
 vm.runInContext(src,ctx);const t=C.create('Prueba');const d=C.division('Libre','Varonil'),other=C.division('Libre','Femenil');t.divisions=[d,other];t.teams=[{id:'team',name:'Equipo',logo:''}];t.entries=[{id:'entry',teamId:'team',divisionId:d.id,groupId:'',roster:[]},{id:'other-entry',teamId:'team',divisionId:other.id,groupId:'',roster:[]}];ctx.window.ui.set(t);return ctx.window.ui;
}
test('team exposes add player; registration survives save/reopen in its own division',async()=>{const ui=app();assert.match(ui.renderTeams(),/Agregar jugador/);await ui.handle('player-new','entry');assert.match(ui.fields(),/Nombre del jugador/);await ui.submit({name:'Ana Pérez',number:'12'});await ui.reopen();assert.equal(ui.read().entries[0].roster[0].name,'Ana Pérez');assert.equal(ui.read().entries[0].roster[0].number,'12');assert.equal(ui.read().entries[1].roster.length,0);await ui.handle('player-new','entry');await assert.rejects(ui.submit({name:'Ana Pérez',number:'8'}),/ya está/);assert.equal(ui.read().entries[0].roster.length,1);});
test('roster opens, edits existing players and adds a batch without losing identity',async()=>{const ui=app();await ui.handle('player-new','entry');await ui.submit({name:'Ana Pérez',number:'12'});const id=ui.read().entries[0].roster[0].id;await ui.handle('roster','entry');assert.match(ui.fields(),/Agregar jugadores/);await ui.submit({name0:'Ana P.',number0:'14',active0:'on',newPlayers:'Luis García | 8\nPedro López | 10'});await ui.reopen();const r=ui.read().entries[0].roster;assert.equal(r.length,3);assert.equal(r[0].id,id);assert.equal(r[0].number,'14');assert.equal(r[2].name,'Pedro López');});
test('public roster opens read-only and rejects add player actions',async()=>{const ui=app(false);await ui.handle('roster','entry');assert.doesNotMatch(ui.fields(),/textarea|name="newPlayers"/);assert.doesNotMatch(ui.renderTeams(),/Agregar jugador/);await assert.rejects(ui.handle('player-new','entry'),/Administrar copa/);});
