const {test}=require('node:test');
const assert=require('node:assert/strict');
const C=require('../js/torneos-core.js');
const createStorage=require('../js/torneos-storage.js');
function fixture(groups=2,size=3){const t=C.create('Copa Independiente');t.start='2026-10-01';t.end='2026-10-03';t.venues=[{id:'court',name:'Cancha 1'},{id:'court2',name:'Cancha 2'}];const d=C.division('Libre','Mixta');t.divisions=[d];for(let g=0;g<groups;g++){d.groups.push({id:'g'+g,name:'Grupo '+g});for(let i=0;i<size;i++){const n=g*size+i;t.teams.push({id:'t'+n,name:'Equipo '+n,logo:''});t.entries.push({id:'e'+n,teamId:'t'+n,divisionId:d.id,groupId:'g'+g,roster:[{id:'p'+n,name:'Jugador '+n,number:'7',active:true}]});}}return t;}
function playedGroups(t){t.games=C.groupGames(t,t.divisions[0].id);for(const g of t.games){g.status='jugado';g.homeScore=100-Number(g.home.slice(1));g.awayScore=100-Number(g.away.slice(1));g.homeStats=[{playerId:t.entries.find(e=>e.id===g.home).roster[0].id,points:g.homeScore,threes:0,fouls:0}];g.awayStats=[{playerId:t.entries.find(e=>e.id===g.away).roster[0].id,points:g.awayScore,threes:0,fouls:0}];g.statsComplete=true;}return t;}
function addBracket(t){const d=t.divisions[0],q=C.qualifiers(t,d.id);d.bracketSeeds=q;t.games.push(...C.bracket(t,d.id,q));return t;}
test('round robin covers each pair exactly once for groups of 3 through 6',()=>{for(let n=3;n<=6;n++){const pairs=C.roundRobin(Array.from({length:n},(_,i)=>'e'+i));const flat=pairs.flat();assert.equal(flat.length,n*(n-1)/2);assert.equal(new Set(flat.map(p=>p.sort().join('|'))).size,flat.length);for(const round of pairs)assert.equal(new Set(round.flat()).size,round.flat().length);for(let i=0;i<n;i++)assert.equal(flat.filter(p=>p.includes('e'+i)).length,n-1);}});
test('same team can enroll in multiple divisions with isolated roster and stats',()=>{const t=playedGroups(fixture()),d=C.division('40+','Varonil');t.divisions.push(d);t.entries.push({id:'other',teamId:'t0',divisionId:d.id,groupId:'',roster:[{id:'other-p',name:'Jugador 0',number:'99'}]});C.validate(t);assert.equal(C.stats(t,d.id).players.length,0);assert.ok(C.stats(t,t.divisions[0].id).players.length);const copy=C.clone(t);copy.entries.at(-1).roster[0].name='Otro';assert.equal(t.entries.at(-1).roster[0].name,'Jugador 0');});
test('cross-division games and duplicate team enrollment are rejected',()=>{const t=fixture(),d=C.division('Libre','Femenil');t.divisions.push(d);t.entries.push({id:'other',teamId:'t0',divisionId:d.id,groupId:'',roster:[]});t.games=C.groupGames(t,t.divisions[0].id);t.games[0].home='other';assert.throws(()=>C.validate(t),/categorías|grupo/);t.games=[];t.entries.push({...t.entries[0],id:'duplicate'});assert.throws(()=>C.validate(t),/ya está inscrito/);});
test('schedule obeys venue occupancy, rest and day range; infeasible schedules fail atomically',()=>{const t=fixture(2,4),games=C.groupGames(t,t.divisions[0].id),config={start:t.start,end:t.end,from:'09:00',to:'20:00',duration:40,gap:10,rest:50,venues:['court','court2']};const scheduled=C.schedule(t,games,config);assert.equal(scheduled.length,12);for(const a of scheduled)for(const b of scheduled){if(a.id===b.id||a.date!==b.date)continue;const diff=Math.abs(C.minutes(a.time)-C.minutes(b.time));if(a.venueId===b.venueId)assert.ok(diff>=50);if([a.home,a.away].some(e=>[b.home,b.away].includes(e)))assert.ok(diff>=90);}assert.throws(()=>C.schedule(t,games,{...config,end:t.start,to:'09:45',venues:['court']}),/No caben/);assert.equal(t.games.length,0);});
test('standings and group qualifiers lead to cross-group single-game semifinals and final',()=>{let t=addBracket(playedGroups(fixture())),d=t.divisions[0];const knockout=t.games.filter(g=>g.phase==='knockout');assert.equal(knockout.length,3);for(const g of knockout.filter(g=>g.round===1)){assert.notEqual(t.entries.find(e=>e.id===g.home).groupId,t.entries.find(e=>e.id===g.away).groupId);t=C.result(t,g.id,{homeScore:20,awayScore:10,forfeit:'ninguno',homeStats:[],awayStats:[],statsComplete:false});}const final=t.games.find(g=>g.phase==='knockout'&&g.round===2);assert.ok(final.home&&final.away);t=C.result(t,final.id,{homeScore:20,awayScore:10,forfeit:'ninguno',homeStats:[],awayStats:[],statsComplete:false});assert.equal(C.winner(t.games.find(g=>g.id===final.id)),final.home);assert.equal(C.stats(t,d.id).games.length,9);});
test('six qualifiers receive two byes; byes never add games or stats',()=>{const t=addBracket(playedGroups(fixture(3,3))),games=t.games.filter(g=>g.phase==='knockout');assert.equal(games.filter(g=>g.bye).length,2);assert.equal(games.filter(g=>!g.bye).length,5);assert.equal(C.stats(t,t.divisions[0].id).games.length,9);C.validate(t);});
test('eight qualifiers produce quarters, semifinals and final',()=>{const t=addBracket(playedGroups(fixture(4,3))),games=t.games.filter(g=>g.phase==='knockout');assert.equal(games.length,7);assert.equal(C.roundName(t,games[0]),'Cuartos de final');assert.equal(C.roundName(t,games.at(-1)),'Final');});
test('one qualifier per group supported and incomplete group cannot qualify',()=>{const t=playedGroups(fixture());t.divisions[0].qualify=1;assert.equal(C.qualifiers(t,t.divisions[0].id).length,2);t.games[0].status='programado';assert.throws(()=>C.qualifiers(t,t.divisions[0].id),/Completa/);});
test('result validates totals, triples, negative scores, draws and wrong roster; pending stats supported',()=>{const t=playedGroups(fixture()),g=t.games[0];assert.throws(()=>C.result(t,g.id,{homeScore:-1}),/inválido/);assert.throws(()=>C.result(t,g.id,{homeScore:g.awayScore}),/ganador/);assert.throws(()=>C.result(t,g.id,{homeScore:999}),/suma individual/);assert.throws(()=>C.result(t,g.id,{homeStats:[{playerId:'foreign',points:1,threes:0,fouls:0}]}),/ajeno/);assert.throws(()=>C.result(t,g.id,{homeStats:[{playerId:g.homeStats[0].playerId,points:1,threes:2,fouls:0}]}),/triples/);assert.equal(C.result(t,g.id,{homeScore:999,statsComplete:false}).games[0].homeScore,999);});
test('forfeit counts team points but no player statistics',()=>{const t=fixture();t.games=C.groupGames(t,t.divisions[0].id);const g=t.games[0];const next=C.result(t,g.id,{homeScore:0,awayScore:20,forfeit:'home',homeStats:[],awayStats:[],statsComplete:true});const rows=C.standings(next,g.divisionId,g.groupId);assert.equal(rows.find(x=>x.entryId===g.home).points,0);assert.equal(rows.find(x=>x.entryId===g.away).points,2);assert.equal(C.stats(next,g.divisionId).players.length,0);});
test('changing prior winner with played downstream match fails; explicit reopen preserves results in trash',()=>{let t=addBracket(playedGroups(fixture())),semi=t.games.find(g=>g.phase==='knockout');for(const g of t.games.filter(g=>g.phase==='knockout'&&g.round===1))t=C.result(t,g.id,{homeScore:30,awayScore:20,forfeit:'ninguno',statsComplete:false});const final=t.games.find(g=>g.phase==='knockout'&&g.round===2);t=C.result(t,final.id,{homeScore:30,awayScore:20,forfeit:'ninguno',statsComplete:false});assert.throws(()=>C.result(t,semi.id,{homeScore:10,awayScore:20,statsComplete:false}),/ya jugada/);const reopened=C.reopen(t,semi.id);assert.equal(reopened.trash.length,2);assert.equal(reopened.games.find(g=>g.id===final.id).home,null);assert.equal(t.games.find(g=>g.id===final.id).status,'jugado');});
test('changing group qualifiers after generating bracket is rejected',()=>{const t=addBracket(playedGroups(fixture())),g=t.games.find(g=>g.phase==='groups'&&[g.home,g.away].includes('e0'));assert.throws(()=>C.result(t,g.id,{homeScore:g.home==='e0'?0:200,awayScore:g.away==='e0'?0:200,statsComplete:false}),/clasificados/);});
test('storage commits tournament, catalog and images atomically and never force-pushes',async()=>{const t=fixture(),calls=[];const s=createStorage({core:C,getToken:()=> 'dummy',fetcher:async(url,init)=>{const path=url.split('piensa')[1],body=init.body?JSON.parse(init.body):null;calls.push({path,method:init.method,body});let data={};let status=200;if(path==='/git/ref/heads/main')data={object:{sha:'head'}};else if(path.startsWith('/contents/')){status=404;}else if(path==='/git/commits/head')data={tree:{sha:'base-tree'}};else if(path==='/git/blobs')data={sha:'blob'+calls.length};else if(path==='/git/trees')data={sha:'tree'};else if(path==='/git/commits')data={sha:'commit'};return {ok:status===200,status,json:async()=>data};}});await s.save(t,null,{['img/torneos/'+t.id+'/test.png']:'cG5n'});const tree=calls.find(c=>c.path==='/git/trees');assert.equal(tree.body.tree.length,3);const update=calls.at(-1);assert.equal(update.path,'/git/refs/heads/main');assert.equal(update.body.force,false);assert.deepEqual(calls.find(c=>c.path==='/git/commits').body.parents,['head']);});
test('storage refuses stale tournament before creating a commit',async()=>{const t=fixture(),calls=[];const s=createStorage({core:C,getToken:()=> 'dummy',fetcher:async(url,init)=>{calls.push(init.method);return {ok:true,status:200,json:async()=>url.includes('/git/ref/')?{object:{sha:'head'}}:{sha:'new',content:Buffer.from(JSON.stringify(t)).toString('base64')}};}});await assert.rejects(s.save(t,'old'),/Otra persona/);assert.deepEqual(calls,['GET','GET']);});
